# Generated by Django 4.2.7 on 2024-03-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit_name', models.CharField(max_length=250)),
                ('icon_link', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('steps', models.CharField(max_length=10000)),
                ('is_warm', models.BooleanField()),
                ('type', models.CharField(max_length=250)),
                ('icon_link', models.CharField(max_length=10000)),
                ('is_public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('is_male', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('bmi', models.FloatField()),
                ('bmr', models.FloatField()),
                ('streak', models.PositiveIntegerField()),
                ('excluded_ingredients', models.ManyToManyField(related_name='user_excluded_ingredient', to='let_me_cook.ingredient')),
                ('favourite_recipes', models.ManyToManyField(to='let_me_cook.recipe')),
                ('stored_ingredients', models.ManyToManyField(related_name='user_stored_ingredient', to='let_me_cook.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='let_me_cook.user'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='let_me_cook.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='flavours',
            field=models.ManyToManyField(to='let_me_cook.flavour'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='let_me_cook.ingredient'),
        ),
        migrations.CreateModel(
            name='CookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='let_me_cook.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='let_me_cook.user')),
            ],
        ),
    ]
