# Generated by Django 4.2.7 on 2024-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_cook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='excluded_ingredients',
            field=models.ManyToManyField(blank=True, related_name='user_excluded_ingredient', to='let_me_cook.ingredient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite_recipes',
            field=models.ManyToManyField(blank=True, to='let_me_cook.recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stored_ingredients',
            field=models.ManyToManyField(blank=True, related_name='user_stored_ingredient', to='let_me_cook.ingredient'),
        ),
    ]
