# Generated by Django 4.2.7 on 2024-04-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_cook', '0002_type_alter_user_excluded_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='let_me_cook.type'),
        ),
    ]
