# Generated by Django 4.2.7 on 2024-04-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_cook', '0003_alter_recipe_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
