# Generated by Django 4.2.7 on 2024-04-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_cook', '0004_rename_user_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('appUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='let_me_cook.appuser')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='let_me_cook.ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='stored_ingredients',
        ),
        migrations.AddField(
            model_name='appuser',
            name='stored_ingredients',
            field=models.ManyToManyField(blank=True, through='let_me_cook.StoredIngredient', to='let_me_cook.ingredient'),
        ),
    ]
