# Generated by Django 4.2.7 on 2024-04-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_cook', '0007_remove_recipe_steps_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='bmr',
        ),
    ]
