# Generated by Django 4.2.7 on 2024-04-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_cook', '0008_remove_appuser_bmi_remove_appuser_bmr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('appUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='let_me_cook.appuser')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='let_me_cook.ingredient')),
            ],
        ),
    ]
